name: Update Global Last Updated Time

on:
  schedule:
    - cron: "0 */4 * * *"  # 每4小时运行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Global Update Time
      env:
        GITHUB_USERNAME: Maychord
      run: |
        LATEST_UPDATE=$(curl -s "https://api.github.com/users/$GITHUB_USERNAME/repos?sort=updated" | jq -r '.[0].updated_at')
        FORMATTED_UPDATE=$(date -u -d "$LATEST_UPDATE" +"%Y-%m-%d %H:%M:%S UTC")

        sed -i "s/全局更新时间：.*/全局更新时间：**$FORMATTED_UPDATE**/g" README.md

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update global last updated time"
        git push
