name: Update Local Time in Sweden

on:
  schedule:
    - cron: "0 */4 * * *"  # 每4小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Local Time in Sweden
      run: |
        # 获取当前 UTC 时间
        UTC_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        
        # 转换为瑞典时间 (CET/CEST 自动处理)
        SWEDEN_TIME=$(TZ=Europe/Stockholm date +"%Y-%m-%d %H:%M:%S %Z")

        # 替换 README.md 中的时间占位符
        sed -i "s|Time:.*CET|Time: $SWEDEN_TIME|g" README.md

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update local time in Sweden"
        git push origin main
